
export const SET_USERNAME = "SET_USERNAME"
export const SET_PASSWORD = "SET_PASSWORD"
export const SET_AUTH = "SET_AUTH"
export const NEW_POST = "NEW_POST"
export const NEW_GENERIC_POST = "NEW_GENERIC_POST"
export const SET_WALL_USERNAME = 'SET_WALL_USERNAME'
export const UPDATE_NEWSFEED = 'UPDATE_NEWSFEED'
export const UPDATE_FRIENDS = 'UPDATE_FRIENDS'
export const SET_ON_GENERIC_WALL = 'SET_ON_GENERIC_WALL'
export const SET_ERROR_TRUE = 'SET_ERROR_TRUE'
export const SET_ERROR_FALSE = 'SET_ERROR_FALSE'
export const UPDATE_SEARCH_TERM = 'UPDATE_SEARCH_TERM'