
export const SET_USERNAME = "SET_USERNAME"
export const SET_PASSWORD = "SET_PASSWORD"
export const SET_AUTH = "SET_AUTH"
export const NEW_POST = "NEW_POST"
export const SET_WALL_USERNAME = 'SET_WALL_USERNAME'
export const UPDATE_NEWSFEED = 'UPDATE_NEWSFEED'